### ISSUE TITLE
Relation to the `atty` crate?

### ISSUE THREAD

**Issue by alexcrichton** [dtolnay/isatty#15]
I'm not personally knowledgeable of the development history of this vs the `atty` crate, but we're in a weird situation in the Rust repository where the RLS uses `isatty` and rustc/Cargo uses `atty` (I think `atty` is also used by ripgrep?). It looks like `atty` differs namely in terms of "weird MSYS detection", although I suspect it's basically equivalent otherwise.

I'm curious, do you know the history here perhaps? I've been surprised by the sheer number of crates that do terminal things (and sad that some, not this library, have spotty support for some platforms). It'd be good if we could consolidate efforts perhaps!

**Comment by dtolnay** [comment]
I don't recall finding `atty` at the time that I needed this functionality for `cargo expand` -- https://github.com/softprops/atty/issues/29. Today the main difference would be the licenses. `atty` is MIT while `isatty` is MIT OR Apache 2.0. I would suggest asking `atty` for a dual license and consolidating on that.

**Comment by alexcrichton** [comment]
Aha excellent point! Thanks for the info, I'll open an issue with `atty`
