### ISSUE TITLE
Is this library ready to go 1.0?

### ISSUE THREAD

**Issue by Byron** [dtolnay/isatty#4]
Thanks for providing this library!

Given the scope, do you think it is ready to go 1.0?

Motivation for this question is me using it in [tokio-cassandra](https://github.com/nhellwig/tokio-cassandra), and I would like to get all dependencies to 1.0 at some point :).

Related to https://github.com/nhellwig/tokio-cassandra/issues/16

**Comment by dtolnay** [comment]
I need to get docs and CI in a better shape before I would do 1.0 but it is not a high priority for me (in contrast to serde 1.0, for example). Is there a reason it makes a difference whether your private dependencies are 1.0? I can understand when people want public dependencies that are exposed in their API to be 1.0 before they can release 1.0 of their own, but tokio-cassandra's dependency on isatty is entirely internal.

**Comment by Byron** [comment]
Thanks for taking the time to answer my question! 
The only reason is that 'it would be nice', especially when a 1.0 seems like it can be achieved relatively easily. Personally I have been pushing my crates towards 1.0 knowing that even a 1.0 doesn't have to be perfect.
I see your point as well - it would certainly be nice to have actual tests for all of this to prevent regressions.
